language: python

services:
  - docker

install: skip

script:
  - docker build -t akshaysachdeva1234/snortfrontend .
  #Push Images to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push akshaysachdeva1234/snortfrontend
  #Deploy on AWS EC2 from Master
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then openssl aes-256-cbc -k "$DECRYPT_KEY" -in akshay.pem.enc -out akshay.pem -d -md sha256; fi
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then chmod 400 akshay.pem; fi
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then ssh -o StrictHostKeyChecking=no -i akshay.pem ubuntu@ec2-54-159-69-0.compute-1.amazonaws.com "cd Snort_rule && sudo git pull"; fi
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then ssh -o StrictHostKeyChecking=no -i akshay.pem ubuntu@ec2-54-159-69-0.compute-1.amazonaws.com "cd Snort_rule && docker-compose down"; fi
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then ssh -o StrictHostKeyChecking=no -i akshay.pem ubuntu@ec2-54-159-69-0.compute-1.amazonaws.com "cd Snort_rule && docker image prune -a -f"; fi
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_EVENT_TYPE == "push" ]; then ssh -o StrictHostKeyChecking=no -i akshay.pem ubuntu@ec2-54-159-69-0.compute-1.amazonaws.com "cd Snort_rule && docker-compose up -d"; fi
